# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix: 
    linux:
      pullName: 'Ubuntu_Pool'
    windows:
      pullName: 'Windows_Pool'

pool:
  name: $(pullName)

steps:
- script: |
    git submodule update --init --recursive
  displayName: 'Fetching submodules'

- script: |
    go build -v
  workingDirectory: $(Build.SourcesDirectory)/go-ipfs/cmd/ipfs
  displayName: 'Building Go Ipfs'
